prepend rank number to all print() invocations
illinois-ceesd/mirgecom pull request #589
Opened 2022-01-10 11:24 UTC by matthiasdiener

**Questions for the review**:
- [ ] Is the scope and purpose of the PR clear?
  - [ ] The PR should have a description.
  - [ ] The PR should have a guide if needed (e.g., an ordering).
- [ ] Is every top-level method and class documented? Are things that should be documented actually so?
- [ ] Is the interface understandable? (I.e. can someone figure out what stuff does?) Is it well-defined?
- [ ] Does the implementation do what the docstring claims?
- [ ] Is everything that is implemented covered by tests?
- [ ] Do you see any immediate risks or performance disadvantages with the design? Example: what do interface normals attach to?

2022-01-10 13:49 UTC, inducer requested changes
Thanks for working on this, but sorry, I'm not a fan. Changing builtins is kind of a no-no IMO. A better approach might be to use logging more pervasively and then install a logging formatter that automatically includes the rank.

2022-01-10 14:01 UTC, matthiasdiener commented
> Thanks for working on this, but sorry, I'm not a fan. Changing builtins is kind of a no-no IMO. A better approach might be to use logging more pervasively and then install a logging formatter that automatically includes the rank.

I was looking at logging formatters as well but didn't find a solution that propagates the formatting across packages; i.e., we can add a formatter to mirgecom logging, but that won't affect grudge etc.

2022-01-10 18:06 UTC, MTCam commented
> > Thanks for working on this, but sorry, I'm not a fan. Changing builtins is kind of a no-no IMO. A better approach might be to use logging more pervasively and then install a logging formatter that automatically includes the rank.
> 
> I was looking at logging formatters as well but didn't find a solution that propagates the formatting across packages; i.e., we can add a formatter to mirgecom logging, but that won't affect logging in grudge etc.

It is a miserable situation to need to debug at the level where you need to see the rank of the writer, but I agree that this is extremely useful when one needs.   If we can turn it on-and-off, it seems only slightly sinful to tweak the internal function.

2022-01-10 20:00 UTC, matthiasdiener commented
Maybe it would be enough to wrap this in an `if 0:` so that it must be manually enabled?

2022-01-11 14:20 UTC, inducer commented
I'm OK with this if it's not turned on unconditionally.

2022-01-11 14:29 UTC, matthiasdiener commented
> I'm OK with this if it's not turned on unconditionally (i.e. on import).

What do you think of 5915121?

2022-01-11 14:40 UTC, MTCam approved these changes
Looks useful.

2022-01-11 15:15 UTC, inducer approved these changes

2022-01-11 15:15 UTC, inducer commented on mirgecom/mpi.py
> +if 0:
```suggestion
def enable_rank_labeled_print():
    """Add docstring here.
    """
```
(and hook into docs)

2022-01-11 19:56 UTC, matthiasdiener commented on mirgecom/mpi.py
> +if 0:
Done, thanks!

2022-01-11 20:15 UTC, MTCam commented on mirgecom/mpi.py
> +if 0:
Even better. This is cool.

2022-01-11 21:14 UTC, merged